version: "3.8"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    volumes:
      - logs-volume:/app/logs
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  logs-volume:

networks:
  app-network:
    driver: bridge
